# Generated by Django 5.2 on 2025-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='symbol',
            new_name='symbolTv',
        ),
        migrations.AddField(
            model_name='asset',
            name='symbolYF',
            field=models.CharField(default='QQQ', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('currency', 'Currency')], max_length=10),
        ),
    ]
